config/routes.rb
Cufcq::Application.routes.draw do

  get "errors/file_not_found"
  get "errors/unprocessable"
  get "errors/internal_server_error"
  root 'static_pages#home'

  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end

  match '/fcqs', to: 'static_pages#help',    via: 'get'
  match '/feedback', to: 'static_pages#feedback',    via: 'get'
  match '/disclaimer', to: 'static_pages#disclaimer',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',    to: 'static_pages#about',    via: 'get'
  match '/thanks',    to: 'static_pages#thanks',    via: 'get'
  match '/ratemybuffs',    to: 'static_pages#ratemybuffs',    via: 'get'

  resources :courses, :except => [:new, :edit, :delete]
    get 'courses/:id/scorecard', to: 'courses#scorecard'
  resources :departments, :except => [:new, :edit, :delete]
    get 'departments/:id/instructors', to: 'departments#instructors'
    get 'departments/:id/courses', to: 'departments#courses'
  resources :instructors, :except => [:new, :edit, :delete]
    get 'instructors/:id/scorecard', to: 'instructors#scorecard'
  resources :fcqs, :except => [:new, :edit, :delete]

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/fcq.rb
VALID_TERMS = { 1 => 'Spring', 4 => 'Summer', 7 => 'Fall' }
VALID_GROUPS = ['TA', 'TTT', 'OTH']
include FcqsHelper
class FcqValidator < ActiveModel::Validator
  def validate(record)
    key = record.yearterm || 0
    key %= 10
    unless VALID_TERMS.key?(key)
      record.errors[:base] << 'term is not valid! must end in 1, 4, 7 to indicate Spring, Summer and Fall respectively'
    end
    unless VALID_GROUPS.include?(record.instr_group)
      record.errors[:base] << 'instructor group is not valid! must be either TTT, TA, or OTH'
    end
    # unless record.pct_c_minus_or_below.nil?
    #   record.errors[:base] << 'instructor group is not valid! must be either TTT, TA, or OTH'
    # end
  end
end
# represents Fcqs as a unque record
class Fcq < ActiveRecord::Base

  # Belongs to
  belongs_to :instructor, counter_cache: true
  belongs_to :course, counter_cache: true
  belongs_to :department, counter_cache: true
  # validates the minimum entries are present
  validates :yearterm, :subject, :crse, :sec, :instructor_last, :instructor_first, :formsrequested, :formsreturned, :campus, :college, presence: true
  # validates entries match established patterns
  validates :yearterm, length: { is: 5 }
  validates :subject, :crse, length: { is: 4 }
  validates :sec, length: { maximum: 3 }
  validates_with FcqValidator
  validates_uniqueness_of :sec, scope: [:crse, :subject, :yearterm, :instructor_last, :instructor_first]
  # before_save :update_counters
  ##################################

  def float_passed
    failed = pct_c_minus_or_below || 1.0
    (1.0 - failed)
  end

  def to_percentage_string(input)
    unless input.between?(0.0, 1.0)
      fail StandardError, 'input not within acceptable bounds'
    end
    val = (input * 100).round(0)
    val = [val, 100].min
    val = [val, 0].max
    "#{val.round}%"
  end

  def pass_rate
    return to_percentage_string(float_passed) unless pct_c_minus_or_below.nil?
    '--'
  end

  def pct_a_string
    return to_percentage_string(pct_a) unless pct_a.nil?
    '--'
  end

  def pct_b_string
    return to_percentage_string(pct_b) unless pct_b.nil?
    '--'
  end

  def pct_c_string
    return to_percentage_string(pct_c) unless pct_c.nil?
    '--'
  end

  def pct_d_string
    return to_percentage_string(pct_d) unless pct_d.nil?
    '--'
  end

  def pct_f_string
    return to_percentage_string(pct_f) unless pct_f.nil?
    '--'
  end

  ###################################

  def course_overall_string
    return out_of_6(courseoverall.round(1)) unless courseoverall.nil?
    '--'
  end

  def instructor_overall_string
    return out_of_6(instructoroverall.round(1)) unless instructoroverall.nil?
    '--'
  end

  ##################################

  def challenge_string
    return out_of_6(challenge.round(1)) unless challenge.nil?
    '--'
  end

  def prior_interest_string
    return out_of_6(priorinterest.round(1)) unless priorinterest.nil?
    '--'
  end

  def howmuchlearned_string
    return out_of_6(howmuchlearned.round(1)) unless howmuchlearned.nil?
    '--'
  end

  def avg_grd_string
    return "#{avg_grd.round(2)} / 4.0" unless avg_grd.nil?
    '--'
  end

  def yearterm_identifier
    "#{subject} #{crse}-#{section_string}, #{semterm}"
  end

  def section_string
    sec.to_s.rjust(3, '0')
  end

  def collected_online?
    return true if onlinefcq == 'OL'
    false
  end

  def uid
    "#{yearterm}#{subject}#{crse}#{sec}"
  end

  def n_withdrawn
    e = n_enroll || 0
    t = n_eot || 0
    [(e - t), 0].max
  end

  def title
    return corrected_course_title unless corrected_course_title.nil?
    capitalized_title
  end

  def capitalized_title
    ctitle = course_title || course.course_title || ''
    ctitle.split.map(&:capitalize).join(' ')
  end

  def correct_title(title)
    write_attribute(:corrected_course_title, title)
  end

  def activity_type_string
    activity_type unless activity_type.nil?
    '--'
  end

  def hours_string
    hours unless hours.nil?
    '--'
  end

  def ld?
    (crse < 3000)
  end

  def ud?
    !(self.ld?) && (crse < 5000)
  end

  def grad?
    (crse >= 5000)
  end

  def rank_string
    return 'Lower Division' if ld?
    return 'Upper Division' if ud?
    'Graduate Level'
  end

  def rank_string_abridged
    return 'ld' if ld?
    return 'ud' if ud?
    'gd'
  end

  def year
    yearterm / 10
  end

  attr_reader :semterm
  def semterm
    (VALID_TERMS[yearterm % 10] + ' ' + year.to_s)
  end

  def self.semterm_from_int(s)
    (VALID_TERMS[s % 10] + ' ' + (s / 10).to_s)
  end

  def summer_fcq?
    ((yearterm % 10) == 4)
  end

  def bad?
    return true if missing_fcq_data?
    (formsreturned < 1)
  end

  def missing_fcq_data?
    (courseoverall.nil?)
  end

  def missing_grade_data?
    avg_grd.nil?
  end

  def color
    return 'box1' if ld?
    return 'box2' if ud?
    'box3'
  end

  def fcq_object
    "#{semterm} #{subject} #{crse}-#{sec} #{title}"
  end

  def fcq_header
    "#{crse}-#{sec}"
  end

  def requested_returned_string
    "#{formsreturned} / #{formsrequested}"
  end

  def instructor_full_name
    "#{instructor_first} #{instructor_last}"
  end

  def recitation?
    return true if course_title == 'REC' || course_title == 'RECITATION'
    unless activity_type.nil?
      return true if activity_type[0..2] == 'LEC' && instr_group == 'TA'
      return true if (activity_type[0..2] == 'REC')
      return false
    end
    true
  end
end

app/controllers/fcqs_controller.rb
class FcqsController < ApplicationController
  before_action :set_fcq, only: [:show, :edit, :update, :destroy]

  # GET /fcqs
  # GET /fcqs.json


  #TODO: Get rid of this in production? 
  def index
    paginate :page => 1, :per_page => 1000
    @fcqs = Fcq.all.page(params[:page]).per_page(10)
  end

  # GET /fcqs/1
  # GET /fcqs/1.json
  def show
  end

  # GET /fcqs/new
  def new
    @fcq = Fcq.new
  end

  # GET /fcqs/1/edit
  def edit
  end

  # POST /fcqs
  # POST /fcqs.json
  def create
    @fcq = Fcq.new(fcq_params)

    respond_to do |format|
      if @fcq.save
        format.html { redirect_to @fcq, notice: 'Fcq was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fcq }
      else
        format.html { render action: 'new' }
        format.json { render json: @fcq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fcqs/1
  # PATCH/PUT /fcqs/1.json
  def update
    respond_to do |format|
      if @fcq.update(fcq_params)
        format.html { redirect_to @fcq, notice: 'Fcq was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fcq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fcqs/1
  # DELETE /fcqs/1.json
  def destroy
    @fcq.destroy
    respond_to do |format|
      format.html { redirect_to fcqs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fcq
      @fcq = Fcq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fcq_params
      params.require(:fcq).permit(:yearterm, :subject, :crse, :sec, :instructor_last, :instructor_first, :formsrequested, :formsreturned)
    end
end

app/helpers/fcqs_helper.rb
module FcqsHelper

  def recitation?(course_title, sec)
    return true if course_title == 'REC' || course_title == 'RECITATION'
    unless activity_type.nil?
      return true if activity_type[0..2] == 'LEC' && instr_group == 'TA'
      return true if (activity_type[0..2] == 'REC')
      return false
    end
    true
  end

  def out_of_6(val)
    "#{val} / 6.0"
  end

end

app/views/fcqs/_form.html.erb
<%= form_for(@fcq) do |f| %>
  <% if @fcq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fcq.errors.count, "error") %> prohibited this fcq from being saved:</h2>

      <ul>
      <% @fcq.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :yearterm %><br>
    <%= f.number_field :yearterm %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :crse %><br>
    <%= f.number_field :crse %>
  </div>
  <div class="field">
    <%= f.label :sec %><br>
    <%= f.number_field :sec %>
  </div>
  <div class="field">
    <%= f.label :instructor_last %><br>
    <%= f.text_field :instructor_last %>
  </div>
  <div class="field">
    <%= f.label :instructor_first %><br>
    <%= f.text_field :instructor_first %>
  </div>
  <div class="field">
    <%= f.label :formsrequested %><br>
    <%= f.number_field :formsrequested %>
  </div>
  <div class="field">
    <%= f.label :formsreturned %><br>
    <%= f.number_field :formsreturned %>
  </div>
  <div class="field">
    <%= f.label :percentage_passed %><br>
    <%= f.text_field :percentage_passed %>
  </div>
  <div class="field">
    <%= f.label :courseoverall %><br>
    <%= f.text_field :courseoverall %>
  </div>
  <div class="field">
    <%= f.label :courseoverall_SD %><br>
    <%= f.text_field :courseoverall_SD %>
  </div>
  <div class="field">
    <%= f.label :instructoroverall %><br>
    <%= f.text_field :instructoroverall %>
  </div>
  <div class="field">
    <%= f.label :instructoroverall_SD %><br>
    <%= f.text_field :instructoroverall_SD %>
  </div>
  <div class="field">
    <%= f.label :hoursperwkinclclass %><br>
    <%= f.text_field :hoursperwkinclclass %>
  </div>
  <div class="field">
    <%= f.label :priorinterest %><br>
    <%= f.text_field :priorinterest %>
  </div>
  <div class="field">
    <%= f.label :instreffective %><br>
    <%= f.text_field :instreffective %>
  </div>
  <div class="field">
    <%= f.label :availability %><br>
    <%= f.text_field :availability %>
  </div>
  <div class="field">
    <%= f.label :challenge %><br>
    <%= f.text_field :challenge %>
  </div>
  <div class="field">
    <%= f.label :howmuchlearned %><br>
    <%= f.text_field :howmuchlearned %>
  </div>
  <div class="field">
    <%= f.label :instrrespect %><br>
    <%= f.text_field :instrrespect %>
  </div>
  <div class="field">
    <%= f.label :course_title %><br>
    <%= f.text_field :course_title %>
  </div>
  <div class="field">
    <%= f.label :campus %><br>
    <%= f.text_field :campus %>
  </div>
  <div class="field">
    <%= f.label :college %><br>
    <%= f.text_field :college %>
  </div>
  <div class="field">
    <%= f.label :instr_group %><br>
    <%= f.text_field :instr_group %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fcqs/edit.html.erb
<h1>Editing fcq</h1>

<%= render 'form' %>

<%= link_to 'Show', @fcq %> |
<%= link_to 'Back', fcqs_path %>

app/views/fcqs/index.html.erb
<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">FCQ Project</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/">Home</a></li>
            <li><a href="/help">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
          <%= text_field_tag :search, params[:search], placeholder: "Search Instructors" %>
          </form>
        </div>
      </div>
    </nav>


     <div class="container-fluid">
          <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav nav-sidebar">
                <li><a href="/departments">Departments<span class="sr-only">(current)</span></a></li>
                <li><a href="/courses">Courses<span class="sr-only">(current)</span></a></li>
              </ul>

      </div>

    <title>FCQs</title>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

          <h2 class="sub-header">Instructors</h2>
          <div class="table-responsive">
            <table class="table table-striped">

              <thead>
                <tr>
                  <th>Corrected Title</th>
                  <th>Yearterm</th>
                  <th>Subject</th>
                  <th>Crse</th>
                  <th>Sec</th>
                  <th>Instructor last</th>
                  <th>Instructor first</th>
                  <th>Forms requested</th>
                  <th>Forms returned</th>
                  <th>Percentage passed</th>
                  <th>Course overall</th>
                  <th>Course overall sd</th>
                  <th>Instructor overall</th>
                  <th>Instructor overall sd</th>
                  <th>Total hours</th>
                  <th>Prior interest</th>
                  <th>Effectiveness</th>
                  <th>Availability</th>
                  <th>Challenge</th>
                  <th>Amount learned</th>
                  <th>Respect</th>
                  <th>Course title</th>
                  <th>Campus</th>
                  <th>College</th>
                  <th>Instructor group</th>
                  <th>is recitation?</th>
                </tr>
              </thead>
              
              <tbody>
               <% @fcqs.each do |fcq| %>
                    <tr>
                      <td><%= fcq.yearterm %></td>
                      <td><%= fcq.subject %></td>
                      <td><%= fcq.crse %></td>
                      <td><%= fcq.sec %></td>
                      <td><%= fcq.instructor_last %></td>
                      <td><%= fcq.instructor_first %></td>
                      <td><%= fcq.formsrequested %></td>
                      <td><%= fcq.formsreturned %></td>
                      <td><%= fcq.percentage_passed %></td>
                      <td><%= fcq.courseoverall %></td>
                      <td><%= fcq.courseoverall_SD %></td>
                      <td><%= fcq.instructoroverall %></td>
                      <td><%= fcq.instructoroverall_SD %></td>
                      <td><%= fcq.hoursperwkinclclass %></td>
                      <td><%= fcq.priorinterest %></td>
                      <td><%= fcq.instreffective %></td>
                      <td><%= fcq.availability %></td>
                      <td><%= fcq.challenge %></td>
                      <td><%= fcq.howmuchlearned %></td>
                      <td><%= fcq.instrrespect %></td>
                      <td><%= fcq.course_title %></td>
                      <td><%= fcq.campus %></td>
                      <td><%= fcq.college %></td>
                      <td><%= fcq.instr_group %></td>
                      <td><%= fcq.recitation? %></td>
                      <td><%= fcq.corrected_course_title %></td>
                    </tr>
                  <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>

app/views/fcqs/new.html.erb
<h1>New fcq</h1>

<%= render 'form' %>

<%= link_to 'Back', fcqs_path %>

app/views/fcqs/show.html.erb
<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  </head>

  <body>
    <title><%= @fcq.capitalized_title %></title>

          <div class="page-header">
            <h1>
              <%= @fcq.yearterm_identifier %>
              <br><small>Course: <%= link_to @fcq.capitalized_title, @fcq.course %></small>
              <br><small>Instructor: <%= link_to @fcq.instructor.name, @fcq.instructor %></small>
              <br><small>Department: <%= link_to @fcq.department.long_name, @fcq.department %></small>
            </h1>
            <!-- Show an alert if fcq data is missing -->
          <% if @fcq.bad? %>
            <% if @fcq.missing_fcq_data? %>
              <div class="alert alert-danger" role="alert"><b>Note: </b> Corruption in records: Fcq data can not be provided. Sorry :(</div>
            <% else %>
              <div class="alert alert-danger" role="alert"><b>Note: </b> This instructor did not turn in any FCQs for this class. As a result no FCQ data can be provided.</div>
              <% end %>
            <% end %>
          <!-- Show a warning if grade data is missing -->
          <% if @fcq.missing_grade_data? %>
            <% if @fcq.summer_fcq? %>
              <div class="alert alert-warning" role="alert"><b>Note: </b> <a href="http://www.colorado.edu/pba/">The Office of Planning and Budget</a> has decided not to give CUFCQ access to Summer Grade data. They have been gracious enough to provide all other data used in CUFCQ. If you enjoy the site and would like to know more, please send them an email at <b><a href="mailto:IR@Colorado.edu">IR@colorado.edu</a></b></div>
            <% elsif @fcq.recitation? %>
              <div class="alert alert-info" role="alert"><b>Recitation: </b> This FCQ is for a recitation or lab associated to <%= link_to @fcq.capitalized_title, @fcq.course %>. Grade data is not recorded here. </b> </div>
            <% else %>
              <div class="alert alert-danger" role="alert"><b>Note: </b> CUFCQ does not have grade data for this course on record. </b> </div>
            <% end %>
          <% end %>

          </div>

          <table class="table table-striped">
            <caption class="text-left"><b>FCQ General</b>
            This table contains identifiable information about the fcq. This includes the yearterm, instructor, course, department, course level, and other identifiable information about the class or instructor</caption>
              <thead>
                <tr>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Year Term</td>
                  <td><%= @fcq.semterm %></td>
                </tr>
                <tr>
                  <td>Course</td>
                  <td><%= link_to @fcq.capitalized_title, @fcq.course %></td>
                </tr>
                <tr>
                  <td>Instructor</td>
                  <td><%= link_to @fcq.instructor.name, @fcq.instructor %></td>
                </tr>
                <tr>
                  <td>Department</td>
                  <td><%= link_to @fcq.department.long_name, @fcq.department %></td>
                </tr>
                <tr>
                  <td>Activity Type</td>
                  <td><%= @fcq.activity_type_string %></td>
                </tr>
                <tr>
                  <td>Credit Hours</td>
                  <td><%= @fcq.hours_string %></td>
                </tr>

                </tbody>
            </table>

            <table class="table table-striped">
            <caption class="text-left"><b>FCQ Meta</b>
            This table contains meta information about the fcq process. This includes the number of requested / returned forms, and how the forms were returned</caption>
              <thead>
                <tr>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Fcqs collected online</td>
                  <td><%= @fcq.collected_online? %></td>
                </tr>
                <!-- Commented out temporarilly -->
                <tr>
                  <td>Forms returned / requested</td>
                  <td><%= @fcq.requested_returned_string %></td>
                </tr>
                </tbody>
            </table>

            <table class="table table-striped">
            <caption class="text-left"><b>FCQ Course Data</b>
            This table contains the averaged results of the fcq survey questions pertaining to the course.</caption>
              <thead>
                <tr>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Course Title</td>
                  <td><%= @fcq.capitalized_title %></td>
                </tr>
                <tr>
                  <td>Course Code</td>
                  <td><%= @fcq.subject %> <%= @fcq.crse %></td>
                </tr>
                <tr>
                  <td>Section</td>
                  <td><%= @fcq.section_string %></td>
                </tr>
                <tr>
                  <td>Course Level</td>
                  <td><%= @fcq.rank_string %></td>
                </tr>
                <tr>
                  <td><abbr title="Students rate the course overall. All ratings are on a scale of 1 to 6." >
                     Course Overall </abbr></td>
                  <td><%= @fcq.course_overall_string %> </td>
                </tr>
                <tr>
                  <td><abbr title="Students rate their personal interest in the material before they enrolled. All ratings are on a scale of 1 to 6." >
                     Prior Interest </abbr></td>
                  <td><%= @fcq.prior_interest_string %></td>
                </tr>
                <tr>
                  <td><abbr title="Students rate the intellectual challenge of the course. All ratings are on a scale of 1 to 6." >
                     Course Challenge </abbr></td>
                  <td><%= @fcq.challenge_string %></td>
                </tr>
                <tr>
                  <td><abbr title="Students rate how much they have learned in this course. All ratings are on a scale of 1 to 6." >
                     Amount Learned </abbr></td>
                  <td><%= @fcq.howmuchlearned_string %></td>
                </tr>
                <tr>
                  <td><abbr title="Students estimate the average number of hours per week they have spent on this course for all course-related work, including attending classes, labs, recitations, readings reviewing notes, writing papers, etc." >
                     Average Workload </abbr></td>
                  <td><%= @fcq.hoursperwkinclclass %> hours per week </td>
                </tr>

                </tbody>
            </table>



            <table class="table table-striped">
            <caption class="text-left"><b>FCQ Instructor Data</b>
             This table contains the averaged results of the fcq survey questions pertaining to the instructor.</caption>
              <thead>
                <tr>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Instructor</td>
                  <td><%= @fcq.instructor.name %></td>
                </tr>
                <tr>
                  <td>Instructor Group</td>
                  <td><abbr title="<%= @fcq.instructor.instr_group_flavor_text %>"> <%= @fcq.instr_group %> </abbr></td>
                </tr>
                  <td><abbr title="Students rate the instructors overall performance. All ratings are on a scale of 1 to 6."> Instructor Overall </abbr></td>
                  <td><% if @fcq.bad? %> -- <% else %><%= @fcq.instructoroverall.round(1) %><%end%></td>
                </tr>
                <tr>
                  <td><abbr title="Students rate the instructor's effectiveness in encouraging interest in the subject. All ratings are on a scale of 1 to 6."> Instructor Effectiveness</abbr></td>
                  <td><% if @fcq.bad? %> -- <% else %><%= @fcq.instreffective.round(1) %><%end%></td>
                </tr>
                <tr>
                  <td><abbr title="Students rate the instructor's availability for course-related assistance such as email, office hours individual appointments, phone contact, etc. All ratings are on a scale of 1 to 6."> Instructor Availability </abbr></td>
                  <td><% if @fcq.bad? %> -- <% else %><%= @fcq.availability.round(1) %><%end%></td>
                </tr>
                <tr>
                  <td><abbr title="Students rate this instructor's instrrespect for and professional treatment of all students regardless of race, color, national origin, sex, age, disability, creed, religion, sexual orientation, or veteran status. All ratings are on a scale of 1 to 6."> Instructor Respect </abbr></td>
                  <td><% if @fcq.bad? %> -- <% else %><%= @fcq.instrrespect.round(1) %><%end%></td>
                </tr>

                </tbody>
            </table>

            <table class="table table-striped">
            <caption class="text-left"><b>Course Enrollment</b>
            This table contains information regarding the composition of students in the class, including the number of graded, pass/fail, withdrawn or incompletes.</caption>
              <thead>
                <tr>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Students Enrolled</td>
                  <td><%= @fcq.n_enroll %></td>
                </tr>
                <tr>
                  <td>Students Withdrawn</td>
                  <td><%= @fcq.n_withdrawn %></td>
                </tr>
                <tr>
                  <td>Students Incomplete</td>
                  <td><%= @fcq.n_incomp %></td>
                </tr>
                <tr>
                  <td>No Credit Students</td>
                  <td><%= @fcq.n_nocred %></td>
                </tr>
                </tbody>
            </table>
            
            <div id="container" style="min-width: 350px; height: 350px; margin: 0 auto">
              <%= render 'layouts/grade_pie' %>
            </div>

            <table class="table table-striped">
            <caption class="text-left"><b>Grade Data</b>
            This table contains information regarding grades given for the class. It contains information regarding the number of students who passed the class, </caption>
              <thead>
                <tr>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><abbr title="Average GPA grade given for the class, with F average being 0.0, D average being 1.0, C average being 2.0, B Average being 3.0, A average being 4.0">Average GPA Grade</abbr></td>
                  <td><%= @fcq.avg_grd_string %></td>
                </tr>
                <tr>
                  <td><abbr title="What percentage of the class received a C grade or higher">Percentage Passed</abbr></td>
                  <td><%= @fcq.pass_rate %></td>
                </tr>

                <tr>
                  <td >Percentage As</td>
                  <td><%= @fcq.pct_a_string %></td>
                </tr>
                <tr>
                  <td >Percentage Bs</td>
                  <td><%= @fcq.pct_b_string %></td>
                </tr>
                <tr>
                  <td>Percentage Cs</td>
                  <td><%= @fcq.pct_c_string %></td>
                </tr>
                <tr>
                  <td>Percentage Ds</td>
                  <td><%= @fcq.pct_d_string %></td>
                </tr>
                <tr>
                  <td>Percentage Fs</td>
                  <td><%= @fcq.pct_f_string %></td>
                </tr>

                </tbody>
            </table>




        </div>