config/routes.rb
Cufcq::Application.routes.draw do

  get "errors/file_not_found"
  get "errors/unprocessable"
  get "errors/internal_server_error"
  root 'static_pages#home'

  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end

  match '/fcqs', to: 'static_pages#help',    via: 'get'
  match '/feedback', to: 'static_pages#feedback',    via: 'get'
  match '/disclaimer', to: 'static_pages#disclaimer',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',    to: 'static_pages#about',    via: 'get'
  match '/thanks',    to: 'static_pages#thanks',    via: 'get'
  match '/ratemybuffs',    to: 'static_pages#ratemybuffs',    via: 'get'

  resources :courses, :except => [:new, :edit, :delete]
    get 'courses/:id/scorecard', to: 'courses#scorecard'
  resources :departments, :except => [:new, :edit, :delete]
    get 'departments/:id/instructors', to: 'departments#instructors'
    get 'departments/:id/courses', to: 'departments#courses'
  resources :instructors, :except => [:new, :edit, :delete]
    get 'instructors/:id/scorecard', to: 'instructors#scorecard'
  resources :fcqs, :except => [:new, :edit, :delete]

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/views/layouts/_course_dashboard.html.erb
<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  </head>

  <body>
  
    <title><%= @course.capitalized_title%></title>
    <div class="container-fluid">
      <div class="row">
<!--         <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a>Course Name: <%= @course.capitalized_title %><span class="sr-only">(current)</span></a></li>
            <li><a href="/departments">Department: <%= @course.department.name %></a></li>

          </ul>
          <ul class="nav nav-sidebar">
            <li><a>Sections Offered: <%= @course.total_sections_offered %></a></li>
            <li><a>Instructors Teaching: <%= @course.instructors.count %> </a></li>
            <li><a>Course Takers: <%= @course.total_students_enrolled %> </a></li>

          </ul>
          <ul class="nav nav-sidebar">
            <li><a>Course Overall:<%= @course.average_courseoverall %></a></li>
            <li><a>Course Challenge: <%= @course.average_challenge %></a></li>
            <li><a>Total Hours: <%= @course.hoursperwkinclclass_string %></a></li>
            <li><a>Prior Interest: <%= @course.average_priorinterest %> </a></li>
            <li><a>Amount Learned: <%= @course.average_howmuchlearned %></a></li>
          </ul>
        </div> -->
        <div class="page-header">
          <h1><%= @course.course_identifier %>
          <br><small>Department: <%= link_to @course.department.long_name, @course.department %></small>
          <br><small><abbr title="Number of FCQs associated with this course since Fall 2008. Includes recitations." >Sections Offered</abbr>: <b><%= @course.total_sections_offered %></b></small>
          <br><small><abbr title="Number of instructors associated with this class since Fall 2008. Includes Teaching Assistants." >Instructors Teaching</abbr>: <b><%= @course.instructors.count %></b></small>
          <br><small><abbr title="Number of students enrolled in this course since Fall 2008." >Students Taught</abbr>:  <b><%= @course.total_students_enrolled %></b></small>
          </h1>
        </div>
        <h1 class="page-header">Course Data</h1>
        <%= render 'layouts/course_graph' %>
          <table class="table table-striped">
            <caption class="text-left"><b>Course Data</b>
            This table contains the averaged results of the fcq survey questions pertaining to the course.</caption>
              <thead>
                <tr>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Course Title</td>
                  <td><%= @course.capitalized_title %></td>
                </tr>
                <tr>
                  <td>Course Code</td>
                  <td><%= @course.subject %> <%= @course.crse %></td>
                </tr>
                <tr>
                  <td>Course Level</td>
                  <td><%= @course.rank_string %></td>
                </tr>
                                </tr>
                <tr>
                  <td><abbr title="Students rate the course overall. All ratings are on a scale of 1 to 6. Average of all course associated FCQs." > Course Overall </abbr></td>
                  <td><%= @course.average_courseoverall %> </td>
                </tr>
                <tr>
                  <td><abbr title="Students rate their personal interest in the material before they enrolled. All ratings are on a scale of 1 to 6. Average of all course associated FCQs." > Prior Interest </abbr></td>
                  <td><%= @course.average_priorinterest %></td>
                </tr>
                <tr>
                  <td><abbr title="Students rate the intellectual challenge of the course. All ratings are on a scale of 1 to 6. Average of all course associated FCQs." > Course Challenge </abbr></td>
                  <td><%= @course.average_challenge %></td>
                </tr>
                <tr>
                  <td><abbr title="Students rate how much they have learned in this course. All ratings are on a scale of 1 to 6. Average of all course associated FCQs." > Amount Learned </abbr></td>
                  <td><%= @course.average_howmuchlearned %></td>
                </tr>
                <tr>
                  <td><abbr title="Students estimate the average number of hours per week they have spent on this course for all course-related work, including attending classes, labs, recitations, readings reviewing notes, writing papers, etc. Statistical Mode of all course associated FCQs." > Mode Average Workload </abbr></td>
                  <td><%= @course.hoursperwkinclclass_string %> hours per week </td>
                </tr>
                

                </tbody>
            </table>

          <h1 class="page-header">Grade Breakdown</h1>
          <%= render 'layouts/course_stack' %>

          <h2 class="sub-header">Past FCQs</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Instructor</th>
                  <th>Course Link</th>
                  <th>Average Work Load </th>
                  <th>Course Overall</th>
                  <th>Average GPA</th>
                  <th>Pass Rate</th> 
                  <th>activity type</th> 
                </tr>
              </thead>
              <tbody>
                <% @course.fcqs.each do |fcq| %>
                <tr>
                    <td><%= link_to fcq.instructor.name, instructor_path(fcq.instructor)%></td>
                    <td><%= link_to fcq.fcq_object, fcq_path(fcq)%></td>
                    <td><%= fcq.hoursperwkinclclass %></td>
                    <td><%= fcq.course_overall_string%></td>
                    <td><%= fcq.avg_grd_string%></td>
                    <td><%= fcq.percentage_passed_string %></td>
                    <td><%= fcq.activity_type_string %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  

app/views/layouts/_course_stack.html.erb
 <% @course.grade_query  %>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>

<script type="text/javascript">
    ready = function() {
    var chart = new Highcharts.Chart({
      title: 
      {
        text: null
        },
        colors: ['#2c7bb6', '#abd9e9', '#ffffbf', '#fdae61', '#d7191c', '#666666'],
      chart: { 
        type: 'area',
        alignTicks: false,
        renderTo: 'stacked' 
        },
        legend: {
            enabled: true
        },
        xAxis: {
            tickPositions: [],
            type: 'category',
            categories: []
        },
        yAxis: [{
          max: 1.0,
          ceiling: 1.0,
          min: 0,
          floor: 0.0,
          title: {
            text: null
            },
            labels: {
                formatter: function () {
                  selector = Math.floor((this.value*100));
                  return ""+selector + "%";
                }
            }
        },
        { // Secondary yAxis
          max: 4.0,
          cieling: 4.0,
          min: 0.0,
          floor: 0.0,
          style: {
                    color: '#333333'
                },
          labels: {
                formatter: function () {
                  arr = ['F','D','C','B','A'];
                  selector = (this.value);
                    return arr[selector] + " avg";
                }
            },
          title: {
            text: null
            },
            opposite: true
        }],
      tooltip: {
        shared: true,
        valueSuffix: ' students',
        formatter: function () {
          var n = this.x%10;
          var y = Math.floor(this.x/10);
          var s = (n == 1) ? "Spring " : n==4 ? "Summer " : n==7 ? "Fall " : "Error ";
          var parsed = s+y+" : "+ this.y;
          // return (this.y >= 1.0) ? parsed : parsed;
          var date = "<b>"+s+y+" :</b><br/>";

          var av = this.points[6].visible ? '' : '<span style="color:#333333">Grade Avg: </span>' + (this.points[6].point.y ) + ' GPA<br/>';
          var aa = this.points[0].visible ? '' : '<span style="color:#2c7bb6">A Grades: </span>' + Math.floor((this.points[0].point.y * 100)) + '%<br/>';
          var bb = this.points[1].visible ? '' : '<span style="color:#abd9e9">B Grades: </span>' + Math.floor((this.points[1].point.y * 100)) + '%<br/>';
          var cc = this.points[2].visible ? '' : '<span style="color:#ffffbf">C Grades: </span>' + Math.floor((this.points[2].point.y * 100)) + '%<br/>';
          var dd = this.points[3].visible ? '' : '<span style="color:#fdae61">D Grades: </span>' + Math.floor((this.points[3].point.y * 100)) + '%<br/>';
          var ff = this.points[4].visible ? '' : '<span style="color:#d7191c">F Grades: </span>' + Math.floor((this.points[4].point.y * 100)) + '%<br/>';
          var ii = this.points[5].visible ? '' : '<span style="color:#666666">Incompletes: </span>' + Math.floor((this.points[5].point.y * 100)) + '%';

          var sum = aa + bb +cc +dd + ff + ii;
          var er = "<br/><b>NOTE:</b> The <i>Office of Planning and Budget</i><br/>did not want to give CUFCQ access to summer grade  <br/>data. They have been gracious enough to provide <br/>all other data used in CUFCQ. If you enjoy the <br/>site and would like to know more, please send them <br/>an email at <b>IR@Colorado.edu</b> ";

          return ((sum >= 90) || (n != 4) ) ? date + av + aa + bb +cc + dd + ff + ii : date + er;

      }
    },
    exporting: {
        buttons: {
            contextButtons: {
                enabled: false,
                menuItems: null
            }
        },
        enabled: true
    },
    plotOptions: {
            area: {
                stacking: 'normal',
                lineColor: '#666666',
                lineWidth: 1,
                marker: {
                    lineWidth: 1,
                    lineColor: '#666666'
                }
            }
        },
    series: [
    {
        data: <%= @course.pct_a_data %>,
        name: "Percentage A Grade"
    },
    {
        data: <%= @course.pct_b_data %>,
        name: "Percentage B Grade"
    },
    {
        data: <%= @course.pct_c_data %>,
        name: "Percentage C Grade"
    },
    {
        data: <%= @course.pct_d_data %>,
        name: "Percentage D Grade"
    },
    {
        data: <%= @course.pct_f_data %>,
        name: "Percentage F Grade"
    },
    {
        data: <%= @course.pct_i_data %>,
        name: "Percentage Incomplete"
    },
    {
            name: 'Grade Average',
            type: 'line',
            yAxis: 1,
            data: <%= @course.grade_data %>,
            marker: {
                enabled: false
            },
            dashStyle: 'shortdot',
            color: '#666666'
    }
  ]
});




  };

$(document).ready(ready);
$(document).on('page:load', ready);
$(document).on('page:change', ready);
</script>
<div id="stacked" style="height: 300px"></div>

app/views/layouts/_course_titlecard.html.erb
<div id="header-wrapper">
	<div id="header" class="course">
		<%= image_tag "course_64.png", alt: "flavor text", title: "flavor text"%> <%= @course.course_title %><br>
		<table><tr><td>Sections Offered</td><td><big><%= @course.total_sections_offered %></big></td><td><div id="triangle-up"></div></td><td><bold><%= @course.total_students_enrolled %></bold></td><td>Students Enrolled</td></tr></table>
	</div>
</div>

app/views/layouts/_department_graph.html.erb
<% @department.overall_query  %>

<script src="http://code.highcharts.com/highcharts.js"></script>

<script type="text/javascript">
    ready = function() {
    
    //overalls
    var chart = new Highcharts.Chart({
      title: {text: null
          },
      chart: { 
        //type: 'area',
        renderTo: 'overalls' },
        legend: {
            enabled: true
        },
        xAxis: {
            tickPositions: [],
            type: 'category',
            categories: []
        },
        yAxis: {
          max: 6,
          min: 0,
          title: {
            text: "enrollment"
            }
        },
      tooltip: {
        formatter: function () {
          var n = this.x%10;
          var y = Math.floor(this.x/10);
          var s = n == 1 ? "Spring " : n==4 ? "Summer " : n==7 ? "Fall " : "Error ";
          // var io = this.points[0].point.y
          // var to = this.points[1].point.y
          // var co = this.points[2].point.y
          return s+y+" : "+this.y;
          //return s+y+'<br/><span style="color:#FFC000">Lower Division: </span>' + io + ' students<br/><span style="color:#FFC000">Upper Division: </span>' + to + ' students<br/><span style="color:#FF8000">Graduate Level: </span>' + co + ' students<br/>'
      }
    },
    exporting: {
        buttons: {
            contextButtons: {
                enabled: false,
                menuItems: null
            }
        },
        enabled: true
    },

    plotOptions: {
                area: {
                    stacking: 'normal',
                    lineColor: '#666666',
                    lineWidth: 1,
                    marker: {
                        lineWidth: 1,
                        lineColor: '#666666'
                    }
                }
            },

    series: [
    {
        data: <%= @department.to_data %>,
        color: '#8bbc20',
        name: "TA Overall"
    },
    {
        data: <%= @department.io_data %>,
        color: '#FFC000',
        name: "Instructor Overall"
    },

    {
        data: <%= @department.co_data %>,
        color: '#FF8000',
        name: "Course Overall"
    }

    ]
    });
};
$(document).ready(ready);
$(document).on('page:load', ready);
$(document).on('page:change', ready);
</script>
</script>


<div id="overalls" style="height: 300px"></div>



<!-- <button id="button">Toggle visibility</button> -->

app/views/layouts/_department_titlecard.html.erb
<div id="header-wrapper">
	<div id="header" class="department">
		 <strong><%= @department.name %></strong><br><br><br><%= @department.long_name %> <br>
		<table><tr><td><bold><%= @department.get_college %></bold></td></tr></table>
	</div>
</div>

app/views/layouts/_fcq_errorbar.html.erb
	<div id="error_header" class="error">
		 <%= image_tag "x_mark_64.png", alt: "Error!", title: "Error!"%><a href="#", alt="The instructor did not return any fcqs for this course.As a result, all the fields of this fcq have no value. This FCQ record is included to indicate the course existed, and was at one point taught." title="The instructor did not return any fcqs for this course. As a result, all the fields of this fcq have no value. This FCQ record is included to indicate the course existed, and was at one point taught.">No FCQS were Returned!</a>
	</div>

app/views/layouts/_fcq_titlecard.html.erb
<div id="header-wrapper">
	<div id="fcq_header" class=<%= @fcq.rank_string_abridged %>>
		 <%= image_tag "fcq_64_w.png", alt: @fcq.rank_string, title: @fcq.rank_string%><%= link_to @fcq.subject, department_path(@fcq.department) %> <%= @fcq.fcq_header %><br><%= link_to @fcq.title, course_path(@fcq.course) %> <br>
		<table><tr><td><bold><%= @fcq.semterm %></bold></td><td><bold><%= link_to @fcq.instructor_full_name, instructor_path(@fcq.instructor) %></bold></td></tr></table>
	</div>
</div>

app/views/layouts/_fcqcard.html.erb
<!-- <input class="spoilerbutton" type="button" value="Show fcqs" onclick="this.value=this.value=='Show fcqs'?'Hide':'Show fcqs';">
<div class="spoiler"><div>
PUT CONTENT YOU WISH TO HIDE HERE
</div></div> -->

<!-- FCQS -->
<table><tr><td><li type=disc> Courses Taught</li></td><td><li type=disc> semesters taught Taught</li></td><td><li type=disc> Courses Taught</li></td></tr></table>
<input class="spoilerbutton" type="button" value="Show fcqs" onclick="this.value=this.value=='Show fcqs'?'Hide fcqs':'Show fcqs';" width=100%>
<div class="spoiler"><div>
<div width=640px align=center>These FCQs are used to generate most other statistics on this page. Click any FCQ to be taken to that page.
<% @instructor.fcqs.each do |fcq| %>
<div id="Data" class=<%= fcq.color%>> <bold><%= fcq.rank_string%></bold> <%= link_to fcq.fcq_object, fcq_path(fcq)%> </div>
<% end %>
</div>
</div></div>
<!-- Courses -->
<input class="spoilerbutton" type="button" value="Show courses" onclick="this.value=this.value=='Show courses'?'Hide courses':'Show courses';" width=100%>
<div class="spoiler"><div>
<div width=640px align=center>These courses were taught / TA'd by this instructor
<% @instructor.courses.each do |course| %>
<div id="Data" class="box5"> <bold>Course</bold> <%= link_to course.course_object, course_path(course)%> </div>
<% end %>
</div>
</div></div>

app/views/layouts/_footer.html.erb
<footer class="footer">


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script>
window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
</script>


  <!-- Add the title in the footer so it otherwise loads the custom title by default from the instructor or course page -->
  <title>CU FCQ</title>
  <nav>
    <ul>
    <li><a class="twitter-share-button" data-counturl="cufcq.com"
  href="https://twitter.com/share">
Tweet
</a></li>
    <li> <div class="fb-share-button" data-href="http://cufcq.com" data-layout="button"></div></li>
      <li> | Created by <a href="http://antsankov.github.io/">Alex Tsankov</a> and <a href="https://github.com/untra">Sam Volin</a></li>
      <li> | <%= link_to "Design by Riley Walker", 'http://www.rileymcmathwalker.com/' %></li>
      <li> | <%= link_to "Github",   'https://github.com/cufcq/cufcq' %></li>
      <li> | <%= link_to "About",   '/about' %></li>
    </ul>
  </nav>

<!-- Google analytics here -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60692178-1', 'auto');
  ga('send', 'pageview');

</script>

</footer>

app/views/layouts/_grade_pie.html.erb
<script src="http://code.highcharts.com/highcharts.js"></script>

<script type="text/javascript">
    var ready;
    ready = function() {
        var chart = new Highcharts.Chart({
          title: {text: null
          },
          chart: {
            plotBackgroundColor: null,
            // plotBorderWidth: 1,
            plotShadow: false,
            renderTo: 'container'
        },
        colors: ['#2c7bb6', '#abd9e9', '#ffffbf', '#fdae61', '#d7191c'],

   // '#492970', '#f28f43', '#77a1e5', '#c42525', '#a6c96a'
   tooltip: {
    pointFormat: '{series.name}<b>{point.percentage:.1f}%</b>'
},
plotOptions: {
    pie: {
        allowPointSelect: true,
        cursor: 'pointer',
        dataLabels: {
            enabled: true,
            format: '<b>{point.name}</b>: {point.percentage:.1f} %',
            style: {
                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
            }
        },
        states: {
            hover: {
             enabled: false
         }
     }
 }
},
series: [{
    type: 'pie',
    name: ' ',
    data: [
    ['A Grade',  <%= @fcq.pct_a %> ],
    ['B Grade',  <%= @fcq.pct_b %> ],
    ['C Grade',  <%= @fcq.pct_c %> ],
    ['D Grade',  <%= @fcq.pct_d %> ],
    ['F Grade',  <%= @fcq.pct_f %> ]
                // ['A',  .2 ],
                // ['B',  .2 ],
                // ['C',  .2 ],
                // ['D',  .2 ],
                // ['F',  .2 ]
                ]
            }]
        });
};

$(document).ready(ready);
$(document).on('page:load', ready);
$(document).on('page:change', ready);
</script>
<!-- <div id="container" style="height: 300px; position: absolute; right: 0px; top: 0px; z-index:-1" ></div> -->
<div id="container" style="height: 200px; float: right; top: -20px; z-index:-1" ></div>
<!-- <div id="container" style="height: 300px" ></div> -->

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top" role="navigation">

  <a class="navbar-brand" style="font-size: 1.75em;" href="/">CU FCQ</a>

    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><%= link_to "Instructors",'/instructors' %></li>
              <li><%= link_to "Courses",'/courses' %></li>
              <li><%= link_to "Departments",'/departments' %></li>
              <li><%= link_to "About", '/about' %></li>
              <li><%= link_to "RateMyBuffs", '/ratemybuffs'%></li>
            </ul>
        </div>
    </div>
</header>
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>Heads Up:</strong> CUFCQ is not going to be updated, and this information may be out of date. Click <%= link_to "here", '/thanks' %> for more info.
</div>

app/views/layouts/_instructor_titlecard.html.erb
<div id="header-wrapper">
	<div id="header" class=<%= @instructor.instructor_type_string %>>
		<%= image_tag "instructor_64.png", alt: @instructor.instr_group_flavor_text, title: @instructor.instr_group_flavor_text%> <%= @instructor.full_name %><br>
		<table>
		<tr><td>Courses Taught</td><td>
		<big><%= @instructor.courses_taught %></big>
		</td><td><div id="triangle-up"></div></td><td><bold><%= @instructor.total_requested %></bold></td><td>Students Taught</td></tr>
		</table>
	</div>
</div>

app/views/layouts/_instructors.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable "Instructor", "instructor_last" %></th>
      <th><%= sortable "Instructor Type", "instructor_group" %></th>
      <th>Department</th>
      <th>Courses Taught</th>
      <th><%= sortable "Earliest Fcq", "earliest_class" %></th>
      <th><%= sortable "Latest Fcq", "latest_class" %></th>
    <th><%= sortable "Instructor Overall", "average_instructor_overall" %></th>
    </tr>
  </thead>
  <tbody>
  <% @instructors.each do |instructor| %>
    <tr>
      <td><%= link_to instructor.name, instructor %></td>
      <td><%= instructor.instr_group %></td>
      <td><%= link_to instructor.department.name, instructor.department %></td>
      <td><%= instructor.courses_taught  %></td>
      <td><%= Fcq.semterm_from_int(instructor.started_teaching) %></td>
      <td><%= Fcq.semterm_from_int(instructor.latest_teaching) %></td>
      <td><%= instructor.average_instructoroverall %></td>
    </tr>
  </tbody>
  <% end %>
</table>
<%= will_paginate @instructors %>

app/views/layouts/_scorecard.html.erb
		<div id="data">
			<ul>
				<li><a href="#" accesskey="1" title="Students rate the instructor's availability for course-related assistance such as email, office hours individual appointments, phone contact, etc. This score is an average of all classes taught by this instructor. All ratings are on a scale of 1 to 6.">
					<strong><%= @instructor.average_availability %> </strong>
					<br>availability</li></a>
				<li><a href="#" accesskey="2" title="Students rate this instructor's instrrespect for and professional treatment of all students regardless of race, color, national origin, sex, age, disability, creed, religion, sexual orientation, or veteran status. This score is an average of all classes taught by this instructor. All ratings are on a scale of 1 to 6.">
			<strong><%= @instructor.average_instrrespect %> </strong>
					<br>instrrespect</li></a>
				<li><a href="#" accesskey="3" title="Students rate the instructors overall performance. This score is an average of all classes taught by this instructor. All ratings are on a scale of 1 to 6.">
					<overall><%= @instructor.average_instructoroverall %> </overall>
					<br>overall</li></a>

				<li><a href="#" accesskey="4" title="Percentage of students that pass their classes when taken with this proffesor. This percentage is an average of all classes taught by this instructor.">
									<strong> <%= @instructor.pass_rate_string %></strong>
					<br>pass-rate</li></a>
				<li><a href="#" accesskey="5" title="Students rate the instructor's instreffective in encouraging interest in the subject. This score is an average of all classes taught by this instructor. All ratings are on a scale of 1 to 6.">
										<strong><%= @instructor.average_instreffective %> </strong>
					<br>effectiveness</li></a>
			</ul>
		</div>